[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Denis_package"
version = "0.1.0"
description = "A simple example Python package"
authors = [{ name="Denis Didylivskyi" }]